version: "3"
services:
  minio:
    image: minio/minio
    container_name: minio
    command: minio server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=user12345
      - MINIO_DEFAULT_BUCKETS=buck1
    networks:
      - sparkpg_network
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - sparkpg_network
    volumes:
      - ./init-minio.sh:/init-minio.sh
      - ./data:/data
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      chmod +x /init-minio.sh;
      /init-minio.sh;
      "
  spark-master:
    image: my-spark
    build: .
    container_name: spark-master
    networks:
      - sparkpg_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-master.sh; tail -f /dev/null"
    ports:
      - "8080:8080"
      - "4040:4040"
      - "7077:7077"
    volumes:
      - spark-events:/opt/spark/events

  spark-worker:
    image: my-spark
    build: .
    container_name: spark-worker1
    networks:
      - sparkpg_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-worker.sh  spark://spark-master:7077; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events

  spark-history-server:
    image: my-spark
    build: .
    container_name: spark-history-server
    networks:
      - sparkpg_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-history-server.sh; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events
    ports:
      - "18080:18080"

networks:
  sparkpg_network:
  mynet:
    driver: bridge
volumes:
  minio_data:
    driver: local
  spark-events:
