# Url for master node
spark.master                           spark://spark-master:7077 
# Enables Logging of events needed for History server
spark.eventLog.enabled                 true
# Output path for master and worker node events                      
spark.eventLog.dir                     /opt/spark/events   
# Input path for history server      
spark.history.fs.logDirectory          /opt/spark/events
spark.hadoop.fs.s3a.endpoint http://minio:9000
spark.hadoop.fs.s3a.access.key user
spark.hadoop.fs.s3a.secret.key user12345
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.connection.timeout 60000
spark.hadoop.fs.s3a.socket.timeout 60000
spark.hadoop.fs.s3a.threads.keepalivetime 60000
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.connection.establish.timeout 30000
spark.hadoop.fs.s3a.connection.request.timeout 30000
spark.hadoop.fs.s3a.retry.limit 3
spark.hadoop.fs.s3a.retry.interval 1000
spark.hadoop.fs.s3a.multipart.purge.age 86400
spark.hadoop.fs.s3a.multipart.size 104857600
spark.io.compression.codec snappy
spark.serializer org.apache.spark.serializer.KryoSerializer
spark.network.timeout 60000
spark.executor.heartbeatInterval 60